# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leader-election'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[deploy]
  strategy = "rolling"
  max_unavailable = 1
  auto_rollback = false
